#version: 2
#jobs:
#  build: #単体テストを実行するジョブ
#    working_directory: ~/my-app
#    docker:
#      - image: ubuntu18:04
#    steps:
#      - checkout
#      - run: apt install gradle
#      - run:
#          name: Run Build
#          command: gradle clean build


version: 2
jobs:
  build: #単体テストを実行するジョブ
    working_directory: ~/
    # working_directory: /home/sasajima/spring/test
    machine: true
    steps:
        - checkout
        - run: |
            docker build -t test .
