#version: 2
#jobs:
#  build: #単体テストを実行するジョブ
#    working_directory: ~/my-app
#    docker:
#      - image: ubuntu18:04
#    steps:
#      - checkout
#      - run: apt install gradle
#      - run:
#          name: Run Build
#          command: gradle clean build


version: 2
jobs:
  build: #単体テストを実行するジョブ
    working_directory: ~/test_dir
    machine: true
    steps:
        - checkout
        - run:
            name: entry point
            command: pwd
        - run:
            name: file list
            command: ls -l
