version: 2
    jobs:
        build:
            machine:
              timezone:
                Asia/Tokyo
              services:
                - docker

dependencies:
  override:
    - echo 0

test:
  override:
    - echo 0

deployment:
  development:
    branch: develop
    commands:
      - pwd:
      - ./deploy.sh:
          environment:
            IMAGE_TAG: $CIRCLE_SHA1
