version: 2
jobs:
    build: #ビルドジョブ
        working_directory: ~/test_dir
        machine: true
        docker_layer_caching: true
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-gradle-{{ checksum "build.gradle" }}
            - run:
                name: Show entry point
                command: pwd
            - run:
                name: Show file list ~/
                command: ls -al ~/
            - run:
                name: Show file list ./
                command: ls -al
            - run:
                name: Gradle build
                command: ./gradlew clean build
            - save_cache:
                paths:
                    - ~/.gradle
                    - .gradle
                key: v1-gradle-{{ checksum "build.gradle" }}
            - persist_to_workspace:
                root: .
                paths:
                  - .

    deploy: # 実行イメージ作成
        working_directory: ~/test_dir
        machine: true
        docker_layer_caching: true
        steps:
            - attach_workspace:
                at: .
            - run:
                name: Change dir
                command: cd infra
            - run:
                name: Show file list
                command: ls -la
                working_directory: infra
            - run:
                name: Docker build
                command: docker-compose build
                working_directory: infra
            - run:
                name: Show docker image list
                command: docker images
                working_directory: infra

workflows:
    version: 2
    build-deploy:  # 任意の名前
        jobs:
            - build
            - deploy:
                requires:
                    - build
