version: 2
jobs:
    build: #ビルドジョブ
        working_directory: ~/test_dir
        machine: true
        docker_layer_caching: true
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-gradle-{{ checksum "build.gradle" }}
            - run:
                name: Show entry point
                command: pwd
            - run:
                name: Show file list ~/
                command: ls -al ~/
            - run:
                name: Show file list ./
                command: ls -al
            - run:
                name: Gradle build
                command: ./gradlew clean build
            - save_cache:
                paths:
                    - ~/.gradle
                    - .gradle
                key: v1-gradle-{{ checksum "build.gradle" }}
            - persist_to_workspace:
                root: .
                paths:
                  - .

    image_push: # 実行イメージ作成
        working_directory: ~/test_dir
        machine: true
        docker_layer_caching: true
        steps:
            - attach_workspace:
                at: .
            - restore_cache:
                keys:
                    - docker-{{ .Branch }}--{{  checksum ".circleci/config.yml"  }}
                path:
                    - ./infra/caches/images.tar
            - run:
                name: Docker read cache
                command: |
                    if [ -e ./infra/caches/images.tar ]; then
                        docker load -i ./infra/caches/images.tar
                    fi
            - run:
                name: Change dir
                command: cd infra
            - run:
                name: Show file list
                command: ls -la
                working_directory: infra
            - run:
                name: Docker build
                command: docker-compose build
                working_directory: infra
            - run:
                name: Show docker image list
                command: docker images
                working_directory: infra
            - run:
                name: Docker cache save
                command: |
                    if [ ! -f ./infra/caches/images.tar ]; then
                        mkdir -p ./infra/caches
                        docker save $(docker images | awk 'NR>=2 && ! /^<none>/{print $1}') -o ./infra/caches/images.tar
                    fi
            - save_cache:
                key: docker-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}
                paths:
                    - ./infra/caches/images.tar
                working_directory: infra

workflows:
    version: 2
    build-deploy:  # 任意の名前
        jobs:
            - build
            - image_push:
                requires:
                    - build
